# Evaluation of test tasks

## Evaluation of test task #1

In [ ]:
res1_cand=1548008755920

In [ ]:
res1_sample= 1548008755920 
res1_score=int (res1_sample==res1_cand) 
res1_score

1

## Evaluation of test task #2

In [ ]:
res2_cand=[ 0., -1.,  1.]
res2_cand

[0.0, -1.0, 1.0]

In [ ]:
res2_sample= [0., -1.,  1.]
import numpy as np 
res2_score = np.mean ([res2_cand[i]==res2_sample[i] for i in range(len(res2_sample)) ])
res2_score

1.0

## Evaluation of test task #3

In [ ]:
res3_cand=['0.69', '0.79', '0.83', '0.74', '0.80', '0.69', '0.76', '0.80']
res3_cand

['0.69', '0.79', '0.83', '0.74', '0.80', '0.69', '0.76', '0.80']

In [ ]:
res3_sample= ['0.69', '0.79', '0.83', '0.74', '0.80', '0.69', '0.76', '0.80']
res3_comparison= [int(float(res3_cand[i])*100)==int(float(res3_sample[i])*100) for i in range(len(res3_sample))]
print (res3_comparison)
res3_score = 3* np.mean (res3_comparison)
res3_score

[True, True, True, True, True, True, True, True]

3.0

In [ ]:
# int(float(res3_cand[0])*100)
[int(float(res3_cand[i])*100)==int(float(res3_sample[i])*100) for i in range(len(res3_sample))]

[True, True, True, True, True, True, True, True]

## Evaluation of test task #4

1. Evaluation is performed to original price values stored in `df_eval.csv`
2. Expected format as in `hometask_completed_sample.csv`

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

### Read example

In [5]:
import pandas as pd 
df_sample= pd.read_csv('/content/drive/MyDrive/Father/camp2021/test_4/hometask_completed_sample.csv', index_col= 0)
df_sample

        rent            dist  nrooms     age size noccup          price
0        624            17.0     2.0  age:41   52      3  226300.000000
1        622            17.0     2.0      21   43      3  213443.498202
2        544             NaN     2.0      52   57      3  176050.000000
3      '423'            17.0     2.0  age:52   51      3  170650.000000
4        288  to center = 17     2.0      52   44      3  171100.000000
...      ...             ...     ...     ...  ...    ...            ...
20635    117            20.0     2.0      25   52      3   39050.000000
20636  '191'            20.0     2.0     mid   63      3   38550.000000
20637    127             NaN     2.0      17   47      3   46150.000000
20638    140            20.0     NaN      18   43      3   42350.000000
20639    NaN            20.0     2.0      16   53      3   44700.000000

[20630 rows x 7 columns]

### Read the solution of candidate

In [7]:
fn_candidate='/content/drive/MyDrive/Father/camp2021/test_4/final_result.csv'
df_to_eval= pd.read_csv(fn_candidate, index_col= 0)
df_to_eval

               price  rent_converted  ...  size_converted  noccup_converted
0      226300.000000      624.000000  ...              52               3.0
2      176050.000000      544.000000  ...              57               3.0
3      170650.000000      423.000000  ...              51               3.0
4      171100.000000      288.000000  ...              44               3.0
6      149600.000000      289.893963  ...              43               3.0
...              ...             ...  ...             ...               ...
20571   82535.893016      256.000000  ...              64               3.0
20597   66801.505705      158.000000  ...              47               3.0
20608   88180.542282      289.893963  ...              75               3.0
20626   68140.516780      162.000000  ...              59               3.0
20631   82814.930438      263.000000  ...              56               3.0

[20630 rows x 7 columns]

### Read the original task to get indices  of missed price values

In [8]:
df_r= pd.read_csv('/content/drive/MyDrive/Father/camp2021/test_4/data_housing.csv', index_col=0)
inices_price_null= df_r[df_r['price'].isnull()].index


y_pred_home= df_to_eval.loc[inices_price_null, 'price'].values
y_pred_home

array([205797.80437997, 185109.7970411 , 138496.31771439, ...,
        88180.54228163,  68140.51677994,  82814.93043779])

### Read the original values of price

In [9]:
df_eval= pd.read_csv('/content/drive/MyDrive/Father/camp2021/test_4/df_eval.csv', index_col=0)
y_test= df_eval.loc[inices_price_null, 'price_orig'].values
y_test

array([179250., 134850.,  76250., ...,  24400.,  46900.,  53600.])

In [10]:
from sklearn.metrics import r2_score
r2_score_sample= r2_score(y_test, y_pred_home)
r2_score_sample

0.07447295746670912

## All together home task eval

In [13]:
def check_hometask(hometask_completed_fn):
    df_to_eval= pd.read_csv(hometask_completed_fn, index_col= 0)
    assert 'price' in list (df_to_eval)

    # read original hometask to get target indices
    df_r= pd.read_csv('/content/drive/MyDrive/Father/camp2021/test_4/data_housing.csv', index_col=0)
    inices_price_null= df_r[df_r['price'].isnull()].index

    try: 
        df_to_eval.loc[inices_price_null]
    except:
        raise Exception ('Provided dataset missed some indices')             
                       
               
    if df_to_eval.loc[inices_price_null,'price'].isnull().sum()!=0:
        raise Exception ('Target price values includes null values ')

    y_pred_home= df_to_eval.loc[inices_price_null, 'price'].values
        
    # read original price values 
    df_eval= pd.read_csv('/content/drive/MyDrive/Father/camp2021/test_4/df_eval.csv', index_col=0)
    y_test= df_eval.loc[inices_price_null, 'price_orig'].values
    
    print ('r2_score =', r2_score(y_test, y_pred_home))
           
    return r2_score(y_test, y_pred_home)
    

r2_score_cand= check_hometask(fn_candidate)
r2_score_cand

r2_score = 0.07447295746670912

0.07447295746670912

# Evaluation score

In [14]:
r2_score_cand

0.07447295746670912

In [15]:
nan_resolved= int(df_to_eval.isnull().sum().sum()> 0)
nan_resolved

0

In [16]:
r2_score_points= 0 
try: 
    if r2_score_cand> r2_score_sample:
        r2_score_points= 3
    elif r2_score_cand>= r2_score_sample*.9:         

        r2_score_points= 2
    else: 
        r2_score_points= 1
except: 
    print ()
    r2_score_points= 0
r2_score_points

2

In [17]:
price_outliers_detected= 1 # or 0 
descr_provided = 1# or 0

In [18]:
res4_score= r2_score_points+ nan_resolved+ price_outliers_detected+ descr_provided
res4_score

4

## task 4 discoveries sample (description)

```python
- 'rent' has 489  values that are not converted to numbers, 
after review it appears the only problem with \'
removed and all values then converted to numbers 
assigned  mean to all missed 

- 'rent' has some negative values. Since this is monthly rent amount and abs values look to be in corresponding range, I replaced all negative values by abs
assigned  mean to all missed 

- 'dist' has 149  values that are not converted to numbers 
review them manbyelly can szee lots of 'to center:' in the value. 
removed the substring and converted to number
removed other str reecords though they have sopme meaning and could be replaced better 

- 'nrooms' has 50 outliers - replaced them by mean 
assigned  mean to all missed 

- 'age' has  values that are not converted to numbers 
review them manbyelly can szee lots of 'age:' in the value. 
removed the substring and converted to number
removed other str reecords though they have sopme meaning and could be replaced better

...

- Most important to detect price outliers !



```

In [ ]:
final_score= res1_score+ res2_score+ res3_score+ res4_score
final_score

10.0